var add =function(n1,n2){return n1+n2};
var n1 =parseInt(prompt("enter a number"));
var n2 =parseInt(prompt("enter another number"));
alert(add(n1,n2));
var subtract =function(n1,n2){ return n1-n2};
var n1= parseInt(prompt("enter a large number"));
var n2= parseInt(prompt("enter a smaller number"));
alert(subtract(n1,n2));
var divide =function(n1,n2){return n1/n2};
var n1= parseInt(prompt("enter a large number"));
var n2= parseInt(prompt("enter a large number"));
alert(divide(n1,n2));
var multiply =function(n1,n2){ return n1*n2};
var n1 =parseInt(prompt("enter a large number"));
var n2 =parseInt(prompt("enter a large number"));
alert(multiply(n1,n2));
